# Test students' skill on Python
<br />
Date: 02/04/2022

by Kreecha Puphaiboon

## Objectives:

- See which State use elec most
- See which categories (RESIDENTIAL, COMMERCIAL, INDUSTRIAL and TRANSPORTATION) use elec most
- Explain out of all categories are there significan difference between each of these.
    - explain how do you find out and explain the result

You read the Excel sheet <b>'US-YTD'</b>

In [6]:
import pandas as pd

dfs = pd.read_excel (r'sales_revenue.xlsx')
dfs

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,RESIDENTIAL,Unnamed: 5,Unnamed: 6,Unnamed: 7,COMMERCIAL,Unnamed: 9,...,Unnamed: 18,Unnamed: 19,OTHER,Unnamed: 21,Unnamed: 22,Unnamed: 23,TOTAL,Unnamed: 25,Unnamed: 26,Unnamed: 27
0,NaN,NaN,NaN,NaN,Revenue,Sales,Customers,Price,Revenue,Sales,...,Customers,Price,Revenue,Sales,Customers,Price,Revenue,Sales,Customers,Price
1,Year,Month,State,Data Status,Thousand Dollars,Megawatthours,Count,Cents/kWh,Thousand Dollars,Megawatthours,...,Count,Cents/kWh,Thousand Dollars,Megawatthours,Count,Cents/kWh,Thousand Dollars,Megawatthours,Count,Cents/kWh
2,2022,1,AK,Preliminary,49487.68,226819.49,294424,21.82,45639.11,239504.98,...,0,0,.,.,.,.,115293.05,579642.48,352318,19.89
3,2022,1,AL,Preliminary,423933.01,3296301.5,2322614,12.86,227035.54,1820104.9,...,0,0,.,.,.,.,828394.93,7769298.4,2706034,10.66
4,2022,1,AR,Preliminary,183556.48,1776158.7,1438917,10.33,86389.41,948173.74,...,2,20.2,.,.,.,.,362400.22,4189367.6,1681324,8.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19633,1990,1,WA,Final,146623,3331947,.,4.4,66956,1596921,...,.,.,11400,330826,.,3.45,310028,8602023,.,3.6
19634,1990,1,WI,Final,106486,1653927,.,6.44,60396,1053545,...,.,.,4030,65383,.,6.16,231107,4242836,.,5.45
19635,1990,1,WV,Final,49876,904654,.,5.51,23564,456243,...,.,.,661,9465,.,6.98,104722,2253097,.,4.65
19636,1990,1,WY,Final,11004,195508,.,5.63,9991,192662,...,.,.,488,15269,.,3.2,44416,1056455,.,4.2
19637,"The sector, Other, was collected from 1990-200...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
#dfs['Unnamed: 25'] = dfs['Unnamed: 25'].fillna(0)

dict = {}
#use enumerate to keep track of index
for i,e in enumerate(dfs['Unnamed: 2'][2:]):
    if dict.get(e) is None:
        dict[e] = 0
    dict[e] += dfs['Unnamed: 25'][i+2]
    #print(dfs['Unnamed: 25'][i+2])

In [8]:
#getting key of maximum value in dictionary <--- Ans1

max(dict, key=dict.get)

'TX'

In [9]:
#read sales_revenue.xlsx in US-YTD worksheet
#I assume that US-YTD is the summary of Monthly-States so I will pick this to answer objective 2
df = pd.read_excel ('sales_revenue.xlsx', 'US-YTD')
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,RESIDENTIAL,Unnamed: 4,Unnamed: 5,Unnamed: 6,COMMERCIAL,Unnamed: 8,Unnamed: 9,...,Unnamed: 17,Unnamed: 18,OTHER,Unnamed: 20,Unnamed: 21,Unnamed: 22,TOTAL,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,NaN,NaN,NaN,Revenue,Sales,Customers,Price,Revenue,Sales,Customers,...,Customers,Price,Revenue,Sales,Customers,Price,Revenue,Sales,Customers,Price
1,Year,MONTH,Data Status,Thousand Dollars,Megawatthours,Count,Cents/kWh,Thousand Dollars,Megawatthours,Count,...,Count,Cents/kWh,Thousand Dollars,Megawatthours,Count,Cents/kWh,Thousand Dollars,Megawatthours,Count,Cents/kWh
2,2022,1,Preliminary,19295982,140593604,138083382,13.724651,12754442,112247715,19107487,...,81,10.879512,.,.,.,.,38187935,336691834,158212379,11.342103
3,2022,.,Preliminary,19295982,140593604,138083382,13.724651,12754442,112247715,19107487,...,81,10.879512,.,.,.,.,38187935,336691834,158212379,11.342103
4,2021,12,Preliminary,16234064,118084631,138914893,13.747822,11911123,106357300,19181468,...,81,10.502692,.,.,.,.,34040573,306581232,159135213,11.10328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
416,1990,3,Final,5442934,71901767,.,7.569959,4191027,57979978,.,...,.,.,458404,7343455,.,6.242348,13626535,214067173,.,6.365542
417,1990,2,Final,5571807,74498370,.,7.479099,4070345,56912068,.,...,.,.,451273,7345620,.,6.14343,13514792,213362594,.,6.33419
418,1990,1,Final,6841300,95420231,.,7.169654,4332195,62498967,.,...,.,.,465357,7767762,.,5.990876,15091189,240874655,.,6.265163
419,1990,.,Final,72378419,924018694,.,7.833004,55116669,751026561,.,...,.,.,5890878,91987720,.,6.403983,178242791,2712554662,.,6.57103
420,"The sector, Other, was collected from 1990-200...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
#filter only '.' in month column
df2 = df.loc[df['Unnamed: 1'] == '.']
df2

,Unnamed: 0,Unnamed: 1,Unnamed: 2,RESIDENTIAL,Unnamed: 4,Unnamed: 5,Unnamed: 6,COMMERCIAL,Unnamed: 8,Unnamed: 9,...,Unnamed: 17,Unnamed: 18,OTHER,Unnamed: 20,Unnamed: 21,Unnamed: 22,TOTAL,Unnamed: 24,Unnamed: 25,Unnamed: 26
3,2022,.,Preliminary,19295982,140593604,138083382,13.724651,12754442,112247715,19107487,...,81,10.879512,.,.,.,.,38187935,336691834,158212379,11.342103
16,2021,.,Preliminary,202640790,1476121129,137820584,13.727924,149502565,1324482037,19022870,...,81.166667,10.23088,.,.,.,.,424516421,3793728701,157865122,11.189952
29,2020,.,Final,192663208,1464605046,136681866,13.154619,136372272,1287439583,18848677,...,82.5,9.902302,.,.,.,.,393639421,3717674481,156522920,10.588324
42,2019,.,Final,187436037,1440288909,135249595,13.01378,145279764,1360876555,18694187,...,83,9.662446,.,.,.,.,401738144,3811150463,154898041,10.541125
55,2018,.,Final,189033288,1469096457,133893626,12.867316,147425877,1381760660,18605401,...,82.583333,9.701602,.,.,.,.,406498314,3860118798,153340274,10.53072
68,2017,.,Final,177661168,1378647742,132579661,12.886625,144241940,1352887694,18359330,...,84.916667,9.683573,.,.,.,.,390322265,3723355974,151779385,10.483077
81,2016,.,Final,177076739,1411058153,131068719,12.549216,142642502,1367191386,18148290,...,83.25,9.627019,.,.,.,.,386509044,3762461630,150055191,10.27277
94,2015,.,Final,177623623,1404096499,129811667,12.650386,144781453,1360751527,17985582,...,78.083333,10.08966,.,.,.,.,391341468,3758992390,148632855,10.410808
107,2014,.,Final,176178008,1407208311,128680294,12.519682,145253154,1352158263,17853836,...,78.5,10.447807,.,.,.,.,393096410,3764700267,147373362,10.441639
120,2013,.,Final,169130640,1394812129,127776941,12.125693,137188490,1337078777,17679466,...,73.916667,10.554599,.,.,.,.,375057738,3724867821,146288214,10.069021
133,2012,.,Final,163280362,1374514704,126832252,11.879128,133898441,1327101211,17728903,...,83.25,10.210621,.,.,.,.,363687487,3694649791,145293583,9.843625
146,2011,.,Final,166713950,1422801095,126143072,11.717305,135926715,1328057442,17637928,...,92.166667,10.463203,.,.,.,.,371049086,3749846184,144508982,9.895048
159,2010,.,Final,166778038,1445708403,125717767,11.536077,135553749,1330199356,17674167,...,238.08333,10.558814,.,.,.,.,368918125,3754841377,144139862,9.825132
172,2009,.,Final,157043560,1364758152,125208777,11.507062,132747022,1306852526,17562150,...,703.16667,10.663683,.,.,.,.,353289274,3596795150,143529126,9.822335
185,2008,.,Final,155496465,1380661746,125037870,11.262459,137035997,1336133489,17582277,...,726.08333,10.711266,.,.,.,.,363583107,3733964624,143395691,9.737187
198,2007,.,Final,148294915,1392241008,102828867,10.651526,128903248,1336315191,14192162,...,958.83333,9.696601,.,.,.,.,343702557,3764560731,117619554,9.129951
211,2006,.,Final,140582344,1351520036,.,10.401795,122913888,1299743681,.,...,.,9.541505,.,.,.,.,326505965,3669918842,.,8.896817
224,2005,.,Final,128392671,1359227117,.,9.446006,109673346,1265783098,.,...,.,8.569343,.,.,.,.,298002811,3660968521,.,8.139999
237,2004,.,Final,115577148,1291981588,.,8.945727,100499885,1229706813,.,...,.,7.182104,.,.,.,.,270119217,3547479479,.,7.614398
250,2003,.,Final,111248929,1275823914,.,8.719771,96263389,1198727614,.,...,.,7.542094,.,.,.,.,259766854,3493734498,.,7.43522
263,2002,.,Final,106833567,1265179870,.,8.444141,87117376,1104496594,.,...,.,.,7123712,105551918,.,6.749012,249410510,3465466011,.,7.197027
276,2001,.,Final,103157869,1201606594,.,8.584995,85741485,1083068538,.,...,.,.,8150827,113173680,.,7.202052,247343101,3394458107,.,7.286674
289,2000,.,Final,98209391,1192446491,.,8.235958,78405330,1055232079,.,...,.,.,7179202,109496283,.,6.556571,233163397,3421414256,.,6.814825
302,1999,.,Final,93482399,1144923081,.,8.16495,72771327,1001995720,.,...,.,.,6795598,106951690,.,6.353895,219896087,3312087083,.,6.6392
315,1998,.,Final,93360134,1130109111,.,8.261161,72574696,979400919,.,...,.,.,6863450,103517594,.,6.630226,219848155,3264230749,.,6.735068
328,1997,.,Final,90703949,1075880097,.,8.430675,70496807,928632781,.,...,.,.,7110099,102900675,.,6.909672,215334328,3145610430,.,6.84555
341,1996,.,Final,90502943,1082511748,.,8.360458,67828214,887445169,.,...,.,.,6741348,97538725,.,6.911458,212608584,3101127032,.,6.855849
354,1995,.,Final,87609593,1042501454,.,8.403786,66364690,862684775,.,...,.,.,6567153,95406996,.,6.883303,207716916,3013286575,.,6.893368
367,1994,.,Final,84552311,1008481693,.,8.38412,63395591,820269465,.,...,.,.,6688996,97830476,.,6.837334,202705976,2934562867,.,6.907536
380,1993,.,Final,82813827,994780825,.,8.324832,61521266,794573364,.,...,.,.,6527940,94943897,.,6.875576,198220188,2861462336,.,6.927234
393,1992,.,Final,76848357,935938788,.,8.210831,58342550,761270531,.,...,.,.,6296221,93442156,.,6.738095,188480315,2763365474,.,6.82068
406,1991,.,Final,76827978,955417354,.,8.0413,57655247,765663602,.,...,.,.,6138291,94338702,.,6.506652,186358705,2762003050,.,6.74723
419,1990,.,Final,72378419,924018694,.,7.833004,55116669,751026561,.,...,.,.,5890878,91987720,.,6.403983,178242791,2712554662,.,6.57103

In [11]:
#select sales column of each categories
RES = df2['Unnamed: 4'].sum()
COM = df2['Unnamed: 8'].sum()
IN = df2['Unnamed: 12'].sum()
#cast '.' to NaN
temp = pd.to_numeric(df2['Unnamed: 16'], errors='coerce')
TRAN = temp.sum()

In [12]:
#print to compare the results, you will see that RESIDENTIAL category use elec the most <--- Ans2
print(f"RESIDENTIAL = {RES} \nCOMMERCIAL = {COM} \nINDUSTRIAL = {IN} \nTRANSPORTATION = {TRAN}")

RESIDENTIAL = 40599561542
COMMERCIAL = 36991254716
INDUSTRIAL = 32021972719
TRANSPORTATION = 141970147.0